pub fn iter_VolumeSliderBar() -> std::vec::IntoIter<SkinImage> {
    vec![
    SkinImage::VolumeSliderBar0,
    SkinImage::VolumeSliderBar1,
    SkinImage::VolumeSliderBar2,
    SkinImage::VolumeSliderBar3,
    SkinImage::VolumeSliderBar4,
    SkinImage::VolumeSliderBar5,
    SkinImage::VolumeSliderBar6,
    SkinImage::VolumeSliderBar7,
    SkinImage::VolumeSliderBar8,
    SkinImage::VolumeSliderBar9,
    SkinImage::VolumeSliderBar10,
    SkinImage::VolumeSliderBar11,
    SkinImage::VolumeSliderBar12,
    SkinImage::VolumeSliderBar13,
    SkinImage::VolumeSliderBar14,
    SkinImage::VolumeSliderBar15,
    SkinImage::VolumeSliderBar16,
    SkinImage::VolumeSliderBar17,
    SkinImage::VolumeSliderBar18,
    SkinImage::VolumeSliderBar19,
    SkinImage::VolumeSliderBar20,
    SkinImage::VolumeSliderBar21,
    SkinImage::VolumeSliderBar22,
    SkinImage::VolumeSliderBar23,
    SkinImage::VolumeSliderBar24,
    SkinImage::VolumeSliderBar25,
    SkinImage::VolumeSliderBar26,
    SkinImage::VolumeSliderBar27,
    ].into_iter()
}

pub fn char_SmallFont(c: char) -> Option<SkinImage> {
    match c {
    'A' => Some(SkinImage::SmallFontA),
    'B' => Some(SkinImage::SmallFontB),
    'C' => Some(SkinImage::SmallFontC),
    'D' => Some(SkinImage::SmallFontD),
    'E' => Some(SkinImage::SmallFontE),
    'F' => Some(SkinImage::SmallFontF),
    'G' => Some(SkinImage::SmallFontG),
    'H' => Some(SkinImage::SmallFontH),
    'I' => Some(SkinImage::SmallFontI),
    'J' => Some(SkinImage::SmallFontJ),
    'K' => Some(SkinImage::SmallFontK),
    'L' => Some(SkinImage::SmallFontL),
    'M' => Some(SkinImage::SmallFontM),
    'N' => Some(SkinImage::SmallFontN),
    'O' => Some(SkinImage::SmallFontO),
    'P' => Some(SkinImage::SmallFontP),
    'Q' => Some(SkinImage::SmallFontQ),
    'R' => Some(SkinImage::SmallFontR),
    'S' => Some(SkinImage::SmallFontS),
    'T' => Some(SkinImage::SmallFontT),
    'U' => Some(SkinImage::SmallFontU),
    'V' => Some(SkinImage::SmallFontV),
    'W' => Some(SkinImage::SmallFontW),
    'X' => Some(SkinImage::SmallFontX),
    'Y' => Some(SkinImage::SmallFontY),
    'Z' => Some(SkinImage::SmallFontZ),
    '"' => Some(SkinImage::SmallFontDoubleQuote),
    '@' => Some(SkinImage::SmallFontAt),
    '0' => Some(SkinImage::SmallFont0),
    '1' => Some(SkinImage::SmallFont1),
    '2' => Some(SkinImage::SmallFont2),
    '3' => Some(SkinImage::SmallFont3),
    '4' => Some(SkinImage::SmallFont4),
    '5' => Some(SkinImage::SmallFont5),
    '6' => Some(SkinImage::SmallFont6),
    '7' => Some(SkinImage::SmallFont7),
    '8' => Some(SkinImage::SmallFont8),
    '9' => Some(SkinImage::SmallFont9),
    '…' => Some(SkinImage::SmallFontEllipsis),
    '.' => Some(SkinImage::SmallFontPeriodMaybe),
    ':' => Some(SkinImage::SmallFontColon),
    '(' => Some(SkinImage::SmallFontLeftParen),
    ')' => Some(SkinImage::SmallFontRightParen),
    '-' => Some(SkinImage::SmallFontHyphen),
    '\'' => Some(SkinImage::SmallFontSingleQuote),
    '!' => Some(SkinImage::SmallFontExclamation),
    '_' => Some(SkinImage::SmallFontUnderscore),
    '+' => Some(SkinImage::SmallFontPlus),
    '\\' => Some(SkinImage::SmallFontBackslash),
    '/' => Some(SkinImage::SmallFontSlash),
    '[' => Some(SkinImage::SmallFontLeftBracket),
    ']' => Some(SkinImage::SmallFontRightBracket),
    '^' => Some(SkinImage::SmallFontCaret),
    '&' => Some(SkinImage::SmallFontAmpersand),
    '%' => Some(SkinImage::SmallFontPercent),
    ',' => Some(SkinImage::SmallFontComma),
    '=' => Some(SkinImage::SmallFontEquals),
    '$' => Some(SkinImage::SmallFontDollar),
    '#' => Some(SkinImage::SmallFontHash),
    _ => None
    }
}

#[derive(Debug, Copy, Clone, fixed_map::Key, strum_macros::AsRefStr, strum_macros::Display)]
pub enum SkinImage {
    ButtonPrev,
    ButtonPlay,
    ButtonPause,
    ButtonStop,
    ButtonNext,
    ButtonEject,
    ButtonPrevPressed,
    ButtonPlayPressed,
    ButtonPausePressed,
    ButtonStopPressed,
    ButtonNextPressed,
    ButtonEjectPressed,
    MainWindow,
    VolumeSliderBar0,
    VolumeSliderBar1,
    VolumeSliderBar2,
    VolumeSliderBar3,
    VolumeSliderBar4,
    VolumeSliderBar5,
    VolumeSliderBar6,
    VolumeSliderBar7,
    VolumeSliderBar8,
    VolumeSliderBar9,
    VolumeSliderBar10,
    VolumeSliderBar11,
    VolumeSliderBar12,
    VolumeSliderBar13,
    VolumeSliderBar14,
    VolumeSliderBar15,
    VolumeSliderBar16,
    VolumeSliderBar17,
    VolumeSliderBar18,
    VolumeSliderBar19,
    VolumeSliderBar20,
    VolumeSliderBar21,
    VolumeSliderBar22,
    VolumeSliderBar23,
    VolumeSliderBar24,
    VolumeSliderBar25,
    VolumeSliderBar26,
    VolumeSliderBar27,
    VolumeSliderButton,
    VolumeSliderButtonPressed,
    SmallFontA,
    SmallFontB,
    SmallFontC,
    SmallFontD,
    SmallFontE,
    SmallFontF,
    SmallFontG,
    SmallFontH,
    SmallFontI,
    SmallFontJ,
    SmallFontK,
    SmallFontL,
    SmallFontM,
    SmallFontN,
    SmallFontO,
    SmallFontP,
    SmallFontQ,
    SmallFontR,
    SmallFontS,
    SmallFontT,
    SmallFontU,
    SmallFontV,
    SmallFontW,
    SmallFontX,
    SmallFontY,
    SmallFontZ,
    SmallFontDoubleQuote,
    SmallFontAt,
    SmallFont0,
    SmallFont1,
    SmallFont2,
    SmallFont3,
    SmallFont4,
    SmallFont5,
    SmallFont6,
    SmallFont7,
    SmallFont8,
    SmallFont9,
    SmallFontEllipsis,
    SmallFontPeriodMaybe,
    SmallFontColon,
    SmallFontLeftParen,
    SmallFontRightParen,
    SmallFontHyphen,
    SmallFontSingleQuote,
    SmallFontExclamation,
    SmallFontUnderscore,
    SmallFontPlus,
    SmallFontBackslash,
    SmallFontSlash,
    SmallFontLeftBracket,
    SmallFontRightBracket,
    SmallFontCaret,
    SmallFontAmpersand,
    SmallFontPercent,
    SmallFontComma,
    SmallFontEquals,
    SmallFontDollar,
    SmallFontHash,
}

pub fn get_skin_load_specs() -> Vec<crate::skin::FileLoadSpec<'static>> {
    vec![
    crate::skin::FileLoadSpec {
    filename: "CBUTTONS.BMP",
    regions: vec![
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 0,
    bottom_right_x: 22,
    bottom_right_y: 18,
    image: SkinImage::ButtonPrev,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 23,
    top_left_y: 0,
    bottom_right_x: 45,
    bottom_right_y: 18,
    image: SkinImage::ButtonPlay,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 46,
    top_left_y: 0,
    bottom_right_x: 68,
    bottom_right_y: 18,
    image: SkinImage::ButtonPause,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 69,
    top_left_y: 0,
    bottom_right_x: 91,
    bottom_right_y: 18,
    image: SkinImage::ButtonStop,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 92,
    top_left_y: 0,
    bottom_right_x: 114,
    bottom_right_y: 18,
    image: SkinImage::ButtonNext,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 115,
    top_left_y: 0,
    bottom_right_x: 137,
    bottom_right_y: 18,
    image: SkinImage::ButtonEject,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 18,
    bottom_right_x: 22,
    bottom_right_y: 36,
    image: SkinImage::ButtonPrevPressed,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 23,
    top_left_y: 18,
    bottom_right_x: 45,
    bottom_right_y: 36,
    image: SkinImage::ButtonPlayPressed,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 46,
    top_left_y: 18,
    bottom_right_x: 68,
    bottom_right_y: 36,
    image: SkinImage::ButtonPausePressed,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 69,
    top_left_y: 18,
    bottom_right_x: 91,
    bottom_right_y: 36,
    image: SkinImage::ButtonStopPressed,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 92,
    top_left_y: 18,
    bottom_right_x: 114,
    bottom_right_y: 36,
    image: SkinImage::ButtonNextPressed,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 115,
    top_left_y: 18,
    bottom_right_x: 137,
    bottom_right_y: 36,
    image: SkinImage::ButtonEjectPressed,
    },
    ]},
    crate::skin::FileLoadSpec {
    filename: "MAIN.BMP",
    regions: vec![
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 0,
    bottom_right_x: 275,
    bottom_right_y: 116,
    image: SkinImage::MainWindow,
    },
    ]},
    crate::skin::FileLoadSpec {
    filename: "VOLUME.BMP",
    regions: vec![
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 0,
    bottom_right_x: 68,
    bottom_right_y: 13,
    image: SkinImage::VolumeSliderBar0,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 15,
    bottom_right_x: 68,
    bottom_right_y: 28,
    image: SkinImage::VolumeSliderBar1,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 30,
    bottom_right_x: 68,
    bottom_right_y: 43,
    image: SkinImage::VolumeSliderBar2,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 45,
    bottom_right_x: 68,
    bottom_right_y: 58,
    image: SkinImage::VolumeSliderBar3,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 60,
    bottom_right_x: 68,
    bottom_right_y: 73,
    image: SkinImage::VolumeSliderBar4,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 75,
    bottom_right_x: 68,
    bottom_right_y: 88,
    image: SkinImage::VolumeSliderBar5,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 90,
    bottom_right_x: 68,
    bottom_right_y: 103,
    image: SkinImage::VolumeSliderBar6,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 105,
    bottom_right_x: 68,
    bottom_right_y: 118,
    image: SkinImage::VolumeSliderBar7,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 120,
    bottom_right_x: 68,
    bottom_right_y: 133,
    image: SkinImage::VolumeSliderBar8,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 135,
    bottom_right_x: 68,
    bottom_right_y: 148,
    image: SkinImage::VolumeSliderBar9,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 150,
    bottom_right_x: 68,
    bottom_right_y: 163,
    image: SkinImage::VolumeSliderBar10,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 165,
    bottom_right_x: 68,
    bottom_right_y: 178,
    image: SkinImage::VolumeSliderBar11,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 180,
    bottom_right_x: 68,
    bottom_right_y: 193,
    image: SkinImage::VolumeSliderBar12,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 195,
    bottom_right_x: 68,
    bottom_right_y: 208,
    image: SkinImage::VolumeSliderBar13,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 210,
    bottom_right_x: 68,
    bottom_right_y: 223,
    image: SkinImage::VolumeSliderBar14,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 225,
    bottom_right_x: 68,
    bottom_right_y: 238,
    image: SkinImage::VolumeSliderBar15,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 240,
    bottom_right_x: 68,
    bottom_right_y: 253,
    image: SkinImage::VolumeSliderBar16,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 255,
    bottom_right_x: 68,
    bottom_right_y: 268,
    image: SkinImage::VolumeSliderBar17,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 270,
    bottom_right_x: 68,
    bottom_right_y: 283,
    image: SkinImage::VolumeSliderBar18,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 285,
    bottom_right_x: 68,
    bottom_right_y: 298,
    image: SkinImage::VolumeSliderBar19,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 300,
    bottom_right_x: 68,
    bottom_right_y: 313,
    image: SkinImage::VolumeSliderBar20,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 315,
    bottom_right_x: 68,
    bottom_right_y: 328,
    image: SkinImage::VolumeSliderBar21,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 330,
    bottom_right_x: 68,
    bottom_right_y: 343,
    image: SkinImage::VolumeSliderBar22,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 345,
    bottom_right_x: 68,
    bottom_right_y: 358,
    image: SkinImage::VolumeSliderBar23,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 360,
    bottom_right_x: 68,
    bottom_right_y: 373,
    image: SkinImage::VolumeSliderBar24,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 375,
    bottom_right_x: 68,
    bottom_right_y: 388,
    image: SkinImage::VolumeSliderBar25,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 390,
    bottom_right_x: 68,
    bottom_right_y: 403,
    image: SkinImage::VolumeSliderBar26,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 405,
    bottom_right_x: 68,
    bottom_right_y: 418,
    image: SkinImage::VolumeSliderBar27,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 422,
    bottom_right_x: 13,
    bottom_right_y: 432,
    image: SkinImage::VolumeSliderButton,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 15,
    top_left_y: 422,
    bottom_right_x: 28,
    bottom_right_y: 432,
    image: SkinImage::VolumeSliderButtonPressed,
    },
    ]},
    crate::skin::FileLoadSpec {
    filename: "TEXT.BMP",
    regions: vec![
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 0,
    bottom_right_x: 4,
    bottom_right_y: 6,
    image: SkinImage::SmallFontA,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 5,
    top_left_y: 0,
    bottom_right_x: 9,
    bottom_right_y: 6,
    image: SkinImage::SmallFontB,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 10,
    top_left_y: 0,
    bottom_right_x: 14,
    bottom_right_y: 6,
    image: SkinImage::SmallFontC,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 15,
    top_left_y: 0,
    bottom_right_x: 19,
    bottom_right_y: 6,
    image: SkinImage::SmallFontD,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 20,
    top_left_y: 0,
    bottom_right_x: 24,
    bottom_right_y: 6,
    image: SkinImage::SmallFontE,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 25,
    top_left_y: 0,
    bottom_right_x: 29,
    bottom_right_y: 6,
    image: SkinImage::SmallFontF,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 30,
    top_left_y: 0,
    bottom_right_x: 34,
    bottom_right_y: 6,
    image: SkinImage::SmallFontG,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 35,
    top_left_y: 0,
    bottom_right_x: 39,
    bottom_right_y: 6,
    image: SkinImage::SmallFontH,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 40,
    top_left_y: 0,
    bottom_right_x: 44,
    bottom_right_y: 6,
    image: SkinImage::SmallFontI,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 45,
    top_left_y: 0,
    bottom_right_x: 49,
    bottom_right_y: 6,
    image: SkinImage::SmallFontJ,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 50,
    top_left_y: 0,
    bottom_right_x: 54,
    bottom_right_y: 6,
    image: SkinImage::SmallFontK,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 55,
    top_left_y: 0,
    bottom_right_x: 59,
    bottom_right_y: 6,
    image: SkinImage::SmallFontL,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 60,
    top_left_y: 0,
    bottom_right_x: 64,
    bottom_right_y: 6,
    image: SkinImage::SmallFontM,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 65,
    top_left_y: 0,
    bottom_right_x: 69,
    bottom_right_y: 6,
    image: SkinImage::SmallFontN,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 70,
    top_left_y: 0,
    bottom_right_x: 74,
    bottom_right_y: 6,
    image: SkinImage::SmallFontO,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 75,
    top_left_y: 0,
    bottom_right_x: 79,
    bottom_right_y: 6,
    image: SkinImage::SmallFontP,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 80,
    top_left_y: 0,
    bottom_right_x: 84,
    bottom_right_y: 6,
    image: SkinImage::SmallFontQ,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 85,
    top_left_y: 0,
    bottom_right_x: 89,
    bottom_right_y: 6,
    image: SkinImage::SmallFontR,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 90,
    top_left_y: 0,
    bottom_right_x: 94,
    bottom_right_y: 6,
    image: SkinImage::SmallFontS,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 95,
    top_left_y: 0,
    bottom_right_x: 99,
    bottom_right_y: 6,
    image: SkinImage::SmallFontT,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 100,
    top_left_y: 0,
    bottom_right_x: 104,
    bottom_right_y: 6,
    image: SkinImage::SmallFontU,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 105,
    top_left_y: 0,
    bottom_right_x: 109,
    bottom_right_y: 6,
    image: SkinImage::SmallFontV,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 110,
    top_left_y: 0,
    bottom_right_x: 114,
    bottom_right_y: 6,
    image: SkinImage::SmallFontW,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 115,
    top_left_y: 0,
    bottom_right_x: 119,
    bottom_right_y: 6,
    image: SkinImage::SmallFontX,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 120,
    top_left_y: 0,
    bottom_right_x: 124,
    bottom_right_y: 6,
    image: SkinImage::SmallFontY,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 125,
    top_left_y: 0,
    bottom_right_x: 129,
    bottom_right_y: 6,
    image: SkinImage::SmallFontZ,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 130,
    top_left_y: 0,
    bottom_right_x: 134,
    bottom_right_y: 6,
    image: SkinImage::SmallFontDoubleQuote,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 135,
    top_left_y: 0,
    bottom_right_x: 139,
    bottom_right_y: 6,
    image: SkinImage::SmallFontAt,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 6,
    bottom_right_x: 4,
    bottom_right_y: 12,
    image: SkinImage::SmallFont0,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 5,
    top_left_y: 6,
    bottom_right_x: 9,
    bottom_right_y: 12,
    image: SkinImage::SmallFont1,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 10,
    top_left_y: 6,
    bottom_right_x: 14,
    bottom_right_y: 12,
    image: SkinImage::SmallFont2,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 15,
    top_left_y: 6,
    bottom_right_x: 19,
    bottom_right_y: 12,
    image: SkinImage::SmallFont3,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 20,
    top_left_y: 6,
    bottom_right_x: 24,
    bottom_right_y: 12,
    image: SkinImage::SmallFont4,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 25,
    top_left_y: 6,
    bottom_right_x: 29,
    bottom_right_y: 12,
    image: SkinImage::SmallFont5,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 30,
    top_left_y: 6,
    bottom_right_x: 34,
    bottom_right_y: 12,
    image: SkinImage::SmallFont6,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 35,
    top_left_y: 6,
    bottom_right_x: 39,
    bottom_right_y: 12,
    image: SkinImage::SmallFont7,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 40,
    top_left_y: 6,
    bottom_right_x: 44,
    bottom_right_y: 12,
    image: SkinImage::SmallFont8,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 45,
    top_left_y: 6,
    bottom_right_x: 49,
    bottom_right_y: 12,
    image: SkinImage::SmallFont9,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 50,
    top_left_y: 6,
    bottom_right_x: 54,
    bottom_right_y: 12,
    image: SkinImage::SmallFontEllipsis,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 55,
    top_left_y: 6,
    bottom_right_x: 59,
    bottom_right_y: 12,
    image: SkinImage::SmallFontPeriodMaybe,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 60,
    top_left_y: 6,
    bottom_right_x: 64,
    bottom_right_y: 12,
    image: SkinImage::SmallFontColon,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 65,
    top_left_y: 6,
    bottom_right_x: 69,
    bottom_right_y: 12,
    image: SkinImage::SmallFontLeftParen,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 70,
    top_left_y: 6,
    bottom_right_x: 74,
    bottom_right_y: 12,
    image: SkinImage::SmallFontRightParen,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 75,
    top_left_y: 6,
    bottom_right_x: 79,
    bottom_right_y: 12,
    image: SkinImage::SmallFontHyphen,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 80,
    top_left_y: 6,
    bottom_right_x: 84,
    bottom_right_y: 12,
    image: SkinImage::SmallFontSingleQuote,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 85,
    top_left_y: 6,
    bottom_right_x: 89,
    bottom_right_y: 12,
    image: SkinImage::SmallFontExclamation,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 90,
    top_left_y: 6,
    bottom_right_x: 94,
    bottom_right_y: 12,
    image: SkinImage::SmallFontUnderscore,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 95,
    top_left_y: 6,
    bottom_right_x: 99,
    bottom_right_y: 12,
    image: SkinImage::SmallFontPlus,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 100,
    top_left_y: 6,
    bottom_right_x: 104,
    bottom_right_y: 12,
    image: SkinImage::SmallFontBackslash,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 105,
    top_left_y: 6,
    bottom_right_x: 109,
    bottom_right_y: 12,
    image: SkinImage::SmallFontSlash,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 110,
    top_left_y: 6,
    bottom_right_x: 114,
    bottom_right_y: 12,
    image: SkinImage::SmallFontLeftBracket,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 115,
    top_left_y: 6,
    bottom_right_x: 119,
    bottom_right_y: 12,
    image: SkinImage::SmallFontRightBracket,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 120,
    top_left_y: 6,
    bottom_right_x: 124,
    bottom_right_y: 12,
    image: SkinImage::SmallFontCaret,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 125,
    top_left_y: 6,
    bottom_right_x: 129,
    bottom_right_y: 12,
    image: SkinImage::SmallFontAmpersand,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 130,
    top_left_y: 6,
    bottom_right_x: 134,
    bottom_right_y: 12,
    image: SkinImage::SmallFontPercent,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 135,
    top_left_y: 6,
    bottom_right_x: 139,
    bottom_right_y: 12,
    image: SkinImage::SmallFontComma,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 140,
    top_left_y: 6,
    bottom_right_x: 144,
    bottom_right_y: 12,
    image: SkinImage::SmallFontEquals,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 145,
    top_left_y: 6,
    bottom_right_x: 149,
    bottom_right_y: 12,
    image: SkinImage::SmallFontDollar,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 150,
    top_left_y: 6,
    bottom_right_x: 154,
    bottom_right_y: 12,
    image: SkinImage::SmallFontHash,
    },
    ]},
    ]
}