pub fn iter_VolumeSliderBar() -> std::vec::IntoIter<SkinImage> {
    vec![
    SkinImage::VolumeSliderBar0,
    SkinImage::VolumeSliderBar1,
    SkinImage::VolumeSliderBar2,
    SkinImage::VolumeSliderBar3,
    SkinImage::VolumeSliderBar4,
    SkinImage::VolumeSliderBar5,
    SkinImage::VolumeSliderBar6,
    SkinImage::VolumeSliderBar7,
    SkinImage::VolumeSliderBar8,
    SkinImage::VolumeSliderBar9,
    SkinImage::VolumeSliderBar10,
    SkinImage::VolumeSliderBar11,
    SkinImage::VolumeSliderBar12,
    SkinImage::VolumeSliderBar13,
    SkinImage::VolumeSliderBar14,
    SkinImage::VolumeSliderBar15,
    SkinImage::VolumeSliderBar16,
    SkinImage::VolumeSliderBar17,
    SkinImage::VolumeSliderBar18,
    SkinImage::VolumeSliderBar19,
    SkinImage::VolumeSliderBar20,
    SkinImage::VolumeSliderBar21,
    SkinImage::VolumeSliderBar22,
    SkinImage::VolumeSliderBar23,
    SkinImage::VolumeSliderBar24,
    SkinImage::VolumeSliderBar25,
    SkinImage::VolumeSliderBar26,
    SkinImage::VolumeSliderBar27,
    ].into_iter()
}

#[derive(Debug, Copy, Clone, fixed_map::Key, strum_macros::AsRefStr, strum_macros::Display)]
pub enum SkinImage {
    ButtonPrev,
    ButtonPlay,
    ButtonPause,
    ButtonStop,
    ButtonNext,
    ButtonEject,
    ButtonPrevPressed,
    ButtonPlayPressed,
    ButtonPausePressed,
    ButtonStopPressed,
    ButtonNextPressed,
    ButtonEjectPressed,
    MainWindow,
    VolumeSliderBar0,
    VolumeSliderBar1,
    VolumeSliderBar2,
    VolumeSliderBar3,
    VolumeSliderBar4,
    VolumeSliderBar5,
    VolumeSliderBar6,
    VolumeSliderBar7,
    VolumeSliderBar8,
    VolumeSliderBar9,
    VolumeSliderBar10,
    VolumeSliderBar11,
    VolumeSliderBar12,
    VolumeSliderBar13,
    VolumeSliderBar14,
    VolumeSliderBar15,
    VolumeSliderBar16,
    VolumeSliderBar17,
    VolumeSliderBar18,
    VolumeSliderBar19,
    VolumeSliderBar20,
    VolumeSliderBar21,
    VolumeSliderBar22,
    VolumeSliderBar23,
    VolumeSliderBar24,
    VolumeSliderBar25,
    VolumeSliderBar26,
    VolumeSliderBar27,
    VolumeSliderButton,
    VolumeSliderButtonPressed,
}

pub fn get_skin_load_specs() -> Vec<crate::skin::FileLoadSpec<'static>> {
    vec![
    crate::skin::FileLoadSpec {
    filename: "CBUTTONS.BMP",
    regions: vec![
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 0,
    bottom_right_x: 22,
    bottom_right_y: 18,
    image: SkinImage::ButtonPrev,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 23,
    top_left_y: 0,
    bottom_right_x: 45,
    bottom_right_y: 18,
    image: SkinImage::ButtonPlay,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 46,
    top_left_y: 0,
    bottom_right_x: 68,
    bottom_right_y: 18,
    image: SkinImage::ButtonPause,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 69,
    top_left_y: 0,
    bottom_right_x: 91,
    bottom_right_y: 18,
    image: SkinImage::ButtonStop,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 92,
    top_left_y: 0,
    bottom_right_x: 114,
    bottom_right_y: 18,
    image: SkinImage::ButtonNext,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 115,
    top_left_y: 0,
    bottom_right_x: 137,
    bottom_right_y: 18,
    image: SkinImage::ButtonEject,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 18,
    bottom_right_x: 22,
    bottom_right_y: 36,
    image: SkinImage::ButtonPrevPressed,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 23,
    top_left_y: 18,
    bottom_right_x: 45,
    bottom_right_y: 36,
    image: SkinImage::ButtonPlayPressed,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 46,
    top_left_y: 18,
    bottom_right_x: 68,
    bottom_right_y: 36,
    image: SkinImage::ButtonPausePressed,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 69,
    top_left_y: 18,
    bottom_right_x: 91,
    bottom_right_y: 36,
    image: SkinImage::ButtonStopPressed,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 92,
    top_left_y: 18,
    bottom_right_x: 114,
    bottom_right_y: 36,
    image: SkinImage::ButtonNextPressed,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 115,
    top_left_y: 18,
    bottom_right_x: 137,
    bottom_right_y: 36,
    image: SkinImage::ButtonEjectPressed,
    },
    ]},
    crate::skin::FileLoadSpec {
    filename: "MAIN.BMP",
    regions: vec![
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 0,
    bottom_right_x: 275,
    bottom_right_y: 116,
    image: SkinImage::MainWindow,
    },
    ]},
    crate::skin::FileLoadSpec {
    filename: "VOLUME.BMP",
    regions: vec![
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 0,
    bottom_right_x: 68,
    bottom_right_y: 13,
    image: SkinImage::VolumeSliderBar0,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 70,
    bottom_right_x: 68,
    bottom_right_y: 83,
    image: SkinImage::VolumeSliderBar1,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 140,
    bottom_right_x: 68,
    bottom_right_y: 153,
    image: SkinImage::VolumeSliderBar2,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 210,
    bottom_right_x: 68,
    bottom_right_y: 223,
    image: SkinImage::VolumeSliderBar3,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 280,
    bottom_right_x: 68,
    bottom_right_y: 293,
    image: SkinImage::VolumeSliderBar4,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 350,
    bottom_right_x: 68,
    bottom_right_y: 363,
    image: SkinImage::VolumeSliderBar5,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 420,
    bottom_right_x: 68,
    bottom_right_y: 433,
    image: SkinImage::VolumeSliderBar6,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 490,
    bottom_right_x: 68,
    bottom_right_y: 503,
    image: SkinImage::VolumeSliderBar7,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 560,
    bottom_right_x: 68,
    bottom_right_y: 573,
    image: SkinImage::VolumeSliderBar8,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 630,
    bottom_right_x: 68,
    bottom_right_y: 643,
    image: SkinImage::VolumeSliderBar9,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 700,
    bottom_right_x: 68,
    bottom_right_y: 713,
    image: SkinImage::VolumeSliderBar10,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 770,
    bottom_right_x: 68,
    bottom_right_y: 783,
    image: SkinImage::VolumeSliderBar11,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 840,
    bottom_right_x: 68,
    bottom_right_y: 853,
    image: SkinImage::VolumeSliderBar12,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 910,
    bottom_right_x: 68,
    bottom_right_y: 923,
    image: SkinImage::VolumeSliderBar13,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 980,
    bottom_right_x: 68,
    bottom_right_y: 993,
    image: SkinImage::VolumeSliderBar14,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1050,
    bottom_right_x: 68,
    bottom_right_y: 1063,
    image: SkinImage::VolumeSliderBar15,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1120,
    bottom_right_x: 68,
    bottom_right_y: 1133,
    image: SkinImage::VolumeSliderBar16,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1190,
    bottom_right_x: 68,
    bottom_right_y: 1203,
    image: SkinImage::VolumeSliderBar17,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1260,
    bottom_right_x: 68,
    bottom_right_y: 1273,
    image: SkinImage::VolumeSliderBar18,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1330,
    bottom_right_x: 68,
    bottom_right_y: 1343,
    image: SkinImage::VolumeSliderBar19,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1400,
    bottom_right_x: 68,
    bottom_right_y: 1413,
    image: SkinImage::VolumeSliderBar20,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1470,
    bottom_right_x: 68,
    bottom_right_y: 1483,
    image: SkinImage::VolumeSliderBar21,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1540,
    bottom_right_x: 68,
    bottom_right_y: 1553,
    image: SkinImage::VolumeSliderBar22,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1610,
    bottom_right_x: 68,
    bottom_right_y: 1623,
    image: SkinImage::VolumeSliderBar23,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1680,
    bottom_right_x: 68,
    bottom_right_y: 1693,
    image: SkinImage::VolumeSliderBar24,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1750,
    bottom_right_x: 68,
    bottom_right_y: 1763,
    image: SkinImage::VolumeSliderBar25,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1820,
    bottom_right_x: 68,
    bottom_right_y: 1833,
    image: SkinImage::VolumeSliderBar26,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 1890,
    bottom_right_x: 68,
    bottom_right_y: 1903,
    image: SkinImage::VolumeSliderBar27,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 0,
    top_left_y: 422,
    bottom_right_x: 13,
    bottom_right_y: 432,
    image: SkinImage::VolumeSliderButton,
    },
    crate::skin::RectLoadSpec {
    top_left_x: 15,
    top_left_y: 422,
    bottom_right_x: 28,
    bottom_right_y: 432,
    image: SkinImage::VolumeSliderButtonPressed,
    },
    ]},
    ]
}